In [1]:
import numpy as np
import pandas as pd
import torch

c:\ProgramData\Miniconda3\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [5]:
x.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
df = pd.DataFrame([x.flatten() for x in x.numpy()])
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
class DataFrameDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.df = df

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        return self.df.iloc[idx].values

[*torch.utils.data.DataLoader(DataFrameDataset(df))]

[tensor([[1, 2, 3]], dtype=torch.int32),
 tensor([[4, 5, 6]], dtype=torch.int32)]